version: '3.4'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - 'formsoft'

    php:
        build: ./docker/php-fpm
        volumes:
            - .:/var/www/html/
            - /var/www/html/node_modules
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - db
        networks:
            - 'formsoft'

    db:
        image: mysql:5.7
        volumes:
            - ./docker/mysql_init:/docker-entrypoint-initdb.d
        ports:
          - "33333:3306"
        environment:
            MYSQL_DATABASE: "app"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "app"
            MYSQL_ROOT_PASSWORD: "root"
        networks:
            - 'formsoft'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "3400:80"
        depends_on:
            - db
        networks:
            - 'formsoft'
networks:
    formsoft:
